(function(exports) {
  'use strict';

  // §4.4 — Maximum 10 active intentions per player
  var MAX_INTENTIONS = 10;

  // Per-player intention store
  var _intentions = {};

  // §4.5 — Valid trigger conditions
  var VALID_TRIGGERS = [
    'player_nearby', 'player_say', 'resource_ready', 'timer',
    'zone_enter', 'health_below', 'item_nearby', 'trade_received',
    'weather_change', 'time_of_day', 'garden_needs', 'ally_nearby'
  ];

  // §4.6 — Valid intention actions
  var VALID_ACTIONS = [
    'say', 'emote', 'move', 'harvest', 'water', 'gift',
    'trade_offer', 'teach', 'follow', 'inspect', 'defend', 'craft', 'compose'
  ];

  // §3.3 — Consent-required action types (cannot be auto-generated by intentions)
  var CONSENT_ACTIONS = ['whisper', 'challenge', 'mentor_offer'];

  var REQUIRED_FIELDS = ['id', 'trigger', 'action', 'priority', 'ttl', 'cooldown', 'max_fires'];

  function registerIntention(playerId, intention) {
    // Validate required fields
    for (var i = 0; i < REQUIRED_FIELDS.length; i++) {
      var field = REQUIRED_FIELDS[i];
      if (intention[field] === undefined || intention[field] === null) {
        return { success: false, error: 'Missing required field: ' + field };
      }
    }

    // §4.4 — Max 10 intentions
    if (!_intentions[playerId]) _intentions[playerId] = [];
    if (_intentions[playerId].length >= MAX_INTENTIONS) {
      return { success: false, error: 'Maximum ' + MAX_INTENTIONS + ' intentions per player' };
    }

    // Store with metadata
    var stored = Object.assign({}, intention, {
      createdAt: intention.createdAt || Date.now(),
      lastFired: intention.lastFired || null,
      fireCount: intention.fireCount || 0
    });

    _intentions[playerId].push(stored);
    return { success: true };
  }

  function clearIntentions(playerId) {
    _intentions[playerId] = [];
  }

  // §4.4 — Intentions are public
  function getIntentions(playerId) {
    return _intentions[playerId] || [];
  }

  // §4.4 — TTL expiry
  function isIntentionExpired(intention, now) {
    now = now || Date.now();
    var createdAt = intention.createdAt || 0;
    var ttlMs = (intention.ttl || 0) * 1000;
    return (now - createdAt) >= ttlMs;
  }

  // §4.4 — Cooldown and max_fires checks
  function canIntentionFire(intention, now) {
    now = now || Date.now();

    // Check max_fires
    if (intention.fireCount >= intention.max_fires) {
      return false;
    }

    // Check cooldown
    if (intention.lastFired !== null && intention.lastFired !== undefined) {
      var cooldownMs = (intention.cooldown || 0) * 1000;
      if ((now - intention.lastFired) < cooldownMs) {
        return false;
      }
    }

    // Check TTL
    if (isIntentionExpired(intention, now)) {
      return false;
    }

    return true;
  }

  function _distance3d(a, b) {
    var dx = (a.x || 0) - (b.x || 0);
    var dy = (a.y || 0) - (b.y || 0);
    var dz = (a.z || 0) - (b.z || 0);
    return Math.sqrt(dx * dx + dy * dy + dz * dz);
  }

  // §4.7 — Evaluate triggers and generate actions
  function evaluateTriggers(playerId, worldState, deltaTime) {
    var actions = [];
    var intentions = getIntentions(playerId);
    var now = Date.now();

    if (!worldState || !worldState.players || !worldState.players[playerId]) {
      return actions;
    }

    var myPos = worldState.players[playerId].position;

    // Sort by priority (higher first)
    var sorted = intentions.slice().sort(function(a, b) {
      return (b.priority || 0) - (a.priority || 0);
    });

    for (var i = 0; i < sorted.length; i++) {
      var intent = sorted[i];
      if (!canIntentionFire(intent, now)) continue;

      var triggered = false;
      var trigger = intent.trigger;

      switch (trigger.condition) {
        case 'player_nearby':
          var distThreshold = trigger.params.distance_lt || 10;
          var playerIds = Object.keys(worldState.players);
          for (var j = 0; j < playerIds.length; j++) {
            var pid = playerIds[j];
            if (pid === playerId) continue;
            var otherPos = worldState.players[pid].position;
            if (_distance3d(myPos, otherPos) < distThreshold) {
              triggered = true;
              break;
            }
          }
          break;

        case 'timer':
          // Timer fires based on interval — simplified: fires if cooldown passed
          triggered = true;
          break;

        case 'zone_enter':
          var myZone = worldState.players[playerId].zone;
          if (myZone === trigger.params.zone_id) {
            triggered = true;
          }
          break;

        default:
          break;
      }

      if (triggered) {
        // Generate action
        var action = {
          type: intent.action.type,
          from: playerId,
          payload: intent.action.params || {}
        };

        // §4.6 — Consent actions cannot be auto-generated
        if (CONSENT_ACTIONS.indexOf(action.type) === -1) {
          actions.push(action);
        }

        // Update fire state
        intent.lastFired = now;
        intent.fireCount++;
      }
    }

    return actions;
  }

  exports.Intentions = {
    MAX_INTENTIONS: MAX_INTENTIONS,
    VALID_TRIGGERS: VALID_TRIGGERS,
    VALID_ACTIONS: VALID_ACTIONS,
    registerIntention: registerIntention,
    clearIntentions: clearIntentions,
    getIntentions: getIntentions,
    isIntentionExpired: isIntentionExpired,
    canIntentionFire: canIntentionFire,
    evaluateTriggers: evaluateTriggers
  };

  if (typeof module !== 'undefined') {
    module.exports = exports.Intentions;
  }
})(typeof module !== 'undefined' ? module.exports : (window.ZION = window.ZION || {}));
