#!/usr/bin/env node
// test_sim_project_manager.js — Auto-generated tests for sim_project_manager
// Generated by sim_forge.py
'use strict';

var Sim = require('../src/js/sim_project_manager.js');

var passed = 0;
var failed = 0;

function assert(condition, message) {
  if (condition) {
    passed++;
  } else {
    failed++;
    console.error('FAIL: ' + message);
  }
}

function assertEqual(actual, expected, message) {
  if (actual === expected) {
    passed++;
  } else {
    failed++;
    console.error('FAIL: ' + message + ' — expected ' + JSON.stringify(expected) + ', got ' + JSON.stringify(actual));
  }
}

// --- initState ---

(function testInitStateEmpty() {
  var state = Sim.initState();
  assert(state && typeof state === 'object', 'initState returns object');
  assert(state._schema && state._schema.collections, 'initState returns state with schema');
  assert(state['boards'] && typeof state['boards'] === 'object', 'initState returns boards object');
  assert(state['tasks'] && typeof state['tasks'] === 'object', 'initState returns tasks object');
  assert(state['sprints'] && typeof state['sprints'] === 'object', 'initState returns sprints object');
})();

(function testInitStateFromSnapshot() {
  var snap = {
    _schema: { collections: {} },
    'boards': { 'boa_snap_1': { id: 'boa_snap_1', name: 'Test' } },
    'tasks': {},
    'sprints': {}
  };
  var state = Sim.initState(snap);
  assert(state['boards']['boa_snap_1'] !== undefined, 'initState restores snapshot data');
  assertEqual(state['boards']['boa_snap_1'].name, 'Test', 'initState restores record name');
  // Deep clone check
  snap['boards']['boa_snap_1'].name = 'Modified';
  assertEqual(state['boards']['boa_snap_1'].name, 'Test', 'initState deep clones snapshot');
})();

// --- boards CRUD ---

(function testCreate_boards() {
  var state = Sim.initState();
  var result = Sim.create_boards(state, { 'name': 'test_name', 'description': 'test_description', 'created_at': 'test_created_at' });
  var record = result.record;
  var newState = result.state;
  assert(record && record.id && record.id.indexOf('boa') === 0, 'create_boards id has boa_ prefix');
  assert(newState['boards'][record.id] !== undefined, 'create_boards stores record');
  assertEqual(Object.keys(state['boards']).length, 0, 'create_boards does not mutate original state');
})();

(function testUpdate_boards() {
  var state = Sim.initState();
  var r = Sim.create_boards(state, { name: 'Original' });
  state = r.state;
  var id = r.record.id;
  var updated = Sim.update_boards(state, id, { name: 'Updated Name' });
  assertEqual(updated['boards'][id].name, 'Updated Name', 'update_boards changes name');
  assertEqual(state['boards'][id].name, 'Original', 'update_boards does not mutate original state');
})();

(function testUpdate_boards_missing() {
  var state = Sim.initState();
  var result = Sim.update_boards(state, 'nonexistent_id', { name: 'X' });
  assert(result === state, 'update_boards nonexistent id returns same state');
})();

(function testDelete_boards() {
  var state = Sim.initState();
  var r = Sim.create_boards(state, { name: 'Delete me' });
  state = r.state;
  var id = r.record.id;
  var deleted = Sim.delete_boards(state, id);
  assert(deleted['boards'][id] === undefined, 'delete_boards removes record');
  assertEqual(Object.keys(state['boards']).length, 1, 'delete_boards does not mutate original state');
})();

(function testDelete_boards_missing() {
  var state = Sim.initState();
  var result = Sim.delete_boards(state, 'nonexistent_id');
  assert(result === state, 'delete_boards nonexistent id returns same state');
})();

// --- tasks CRUD ---

(function testCreate_tasks() {
  var state = Sim.initState();
  var result = Sim.create_tasks(state, { 'title': 'test_title', 'status': 'active', 'assignee': 'test_assignee' });
  var record = result.record;
  var newState = result.state;
  assert(record && record.id && record.id.indexOf('tas') === 0, 'create_tasks id has tas_ prefix');
  assert(newState['tasks'][record.id] !== undefined, 'create_tasks stores record');
  assertEqual(Object.keys(state['tasks']).length, 0, 'create_tasks does not mutate original state');
})();

(function testUpdate_tasks() {
  var state = Sim.initState();
  var r = Sim.create_tasks(state, { name: 'Original' });
  state = r.state;
  var id = r.record.id;
  var updated = Sim.update_tasks(state, id, { name: 'Updated Name' });
  assertEqual(updated['tasks'][id].name, 'Updated Name', 'update_tasks changes name');
  assertEqual(state['tasks'][id].name, 'Original', 'update_tasks does not mutate original state');
})();

(function testUpdate_tasks_missing() {
  var state = Sim.initState();
  var result = Sim.update_tasks(state, 'nonexistent_id', { name: 'X' });
  assert(result === state, 'update_tasks nonexistent id returns same state');
})();

(function testDelete_tasks() {
  var state = Sim.initState();
  var r = Sim.create_tasks(state, { name: 'Delete me' });
  state = r.state;
  var id = r.record.id;
  var deleted = Sim.delete_tasks(state, id);
  assert(deleted['tasks'][id] === undefined, 'delete_tasks removes record');
  assertEqual(Object.keys(state['tasks']).length, 1, 'delete_tasks does not mutate original state');
})();

(function testDelete_tasks_missing() {
  var state = Sim.initState();
  var result = Sim.delete_tasks(state, 'nonexistent_id');
  assert(result === state, 'delete_tasks nonexistent id returns same state');
})();

// --- sprints CRUD ---

(function testCreate_sprints() {
  var state = Sim.initState();
  var result = Sim.create_sprints(state, { 'name': 'test_name', 'start_date': 'test_start_date', 'end_date': 'test_end_date' });
  var record = result.record;
  var newState = result.state;
  assert(record && record.id && record.id.indexOf('spr') === 0, 'create_sprints id has spr_ prefix');
  assert(newState['sprints'][record.id] !== undefined, 'create_sprints stores record');
  assertEqual(Object.keys(state['sprints']).length, 0, 'create_sprints does not mutate original state');
})();

(function testUpdate_sprints() {
  var state = Sim.initState();
  var r = Sim.create_sprints(state, { name: 'Original' });
  state = r.state;
  var id = r.record.id;
  var updated = Sim.update_sprints(state, id, { name: 'Updated Name' });
  assertEqual(updated['sprints'][id].name, 'Updated Name', 'update_sprints changes name');
  assertEqual(state['sprints'][id].name, 'Original', 'update_sprints does not mutate original state');
})();

(function testUpdate_sprints_missing() {
  var state = Sim.initState();
  var result = Sim.update_sprints(state, 'nonexistent_id', { name: 'X' });
  assert(result === state, 'update_sprints nonexistent id returns same state');
})();

(function testDelete_sprints() {
  var state = Sim.initState();
  var r = Sim.create_sprints(state, { name: 'Delete me' });
  state = r.state;
  var id = r.record.id;
  var deleted = Sim.delete_sprints(state, id);
  assert(deleted['sprints'][id] === undefined, 'delete_sprints removes record');
  assertEqual(Object.keys(state['sprints']).length, 1, 'delete_sprints does not mutate original state');
})();

(function testDelete_sprints_missing() {
  var state = Sim.initState();
  var result = Sim.delete_sprints(state, 'nonexistent_id');
  assert(result === state, 'delete_sprints nonexistent id returns same state');
})();

// --- Schema ---

(function testGetSchema() {
  Sim.initState();
  var schema = Sim.getSchema();
  assert(schema && schema.collections, 'getSchema returns collections');
  assert(schema.collections['boards'], 'schema has boards collection');
  assert(schema.collections['boards'].fields.indexOf('name') !== -1, 'schema boards has name field');
  assert(schema.collections['boards'].fields.indexOf('description') !== -1, 'schema boards has description field');
  assert(schema.collections['tasks'], 'schema has tasks collection');
  assert(schema.collections['tasks'].fields.indexOf('title') !== -1, 'schema tasks has title field');
  assert(schema.collections['tasks'].fields.indexOf('status') !== -1, 'schema tasks has status field');
  assert(schema.collections['sprints'], 'schema has sprints collection');
  assert(schema.collections['sprints'].fields.indexOf('name') !== -1, 'schema sprints has name field');
  assert(schema.collections['sprints'].fields.indexOf('start_date') !== -1, 'schema sprints has start_date field');
})();

// --- applyAction ---

(function testApplyAction_create() {
  var state = Sim.initState();
  var msg = {
    from: 'user1',
    payload: {
      action: 'create_boards',
      data: { name: 'Action Created' }
    }
  };
  var s2 = Sim.applyAction(state, msg);
  var items = Sim.query(s2, 'boards', null);
  assertEqual(items.length, 1, 'applyAction create adds record');
  assertEqual(items[0].name, 'Action Created', 'applyAction create passes name');
  assertEqual(items[0].owner, 'user1', 'applyAction sets owner from msg.from');
})();

(function testApplyAction_update() {
  var state = Sim.initState();
  var r = Sim.create_boards(state, { name: 'Before' });
  state = r.state;
  var id = r.record.id;
  var msg = {
    from: 'user1',
    payload: {
      action: 'update_boards',
      data: { id: id, name: 'After' }
    }
  };
  var s2 = Sim.applyAction(state, msg);
  assertEqual(s2['boards'][id].name, 'After', 'applyAction update changes name');
})();

(function testApplyAction_delete() {
  var state = Sim.initState();
  var r = Sim.create_boards(state, { name: 'Gone' });
  state = r.state;
  var id = r.record.id;
  var msg = {
    from: 'user1',
    payload: {
      action: 'delete_boards',
      data: { id: id }
    }
  };
  var s2 = Sim.applyAction(state, msg);
  assert(s2['boards'][id] === undefined, 'applyAction delete removes record');
})();

(function testApplyAction_unknown() {
  var state = Sim.initState();
  var msg = { from: 'x', payload: { action: 'nonexistent_action_xyz', data: {} } };
  var s2 = Sim.applyAction(state, msg);
  assert(s2 === state, 'applyAction unknown action returns same state');
})();

// --- Edge cases ---

(function testCreate_missing_fields() {
  // Create with no data — should not throw, uses defaults
  var state = Sim.initState();
  var result = Sim.create_boards(state, {});
  assert(result && result.record && result.record.id, 'create with empty data sets an id');
})();

(function testUpdate_nonexistent_id() {
  var state = Sim.initState();
  var result = Sim.update_boards(state, 'nonexistent', { name: 'X' });
  assert(result === state, 'update nonexistent id returns same state unchanged');
})();

(function testDelete_nonexistent_id() {
  var state = Sim.initState();
  var result = Sim.delete_boards(state, 'nonexistent');
  assert(result === state, 'delete nonexistent id returns same state');
})();

// --- Snapshot roundtrip ---

(function testSnapshotRoundtrip() {
  var state = Sim.initState();
  var r_boards = Sim.create_boards(state, { name: 'Persist boards' });
  state = r_boards.state;
  var r_tasks = Sim.create_tasks(state, { name: 'Persist tasks' });
  state = r_tasks.state;
  var r_sprints = Sim.create_sprints(state, { name: 'Persist sprints' });
  state = r_sprints.state;
  var json = JSON.stringify(state);
  var restored = Sim.initState(JSON.parse(json));
  assertEqual(Object.keys(restored['boards']).length, 1, 'snapshot restores boards');
  assertEqual(Object.keys(restored['tasks']).length, 1, 'snapshot restores tasks');
  assertEqual(Object.keys(restored['sprints']).length, 1, 'snapshot restores sprints');
})();

(function testGetState() {
  var state = Sim.initState();
  var got = Sim.getState();
  assert(got && typeof got === 'object', 'getState returns object');
  assert(got._schema !== undefined, 'getState includes schema');
})();

(function testQuery() {
  var state = Sim.initState();
  var r1 = Sim.create_boards(state, { name: 'A', status: 'active' });
  state = r1.state;
  var r2 = Sim.create_boards(state, { name: 'B', status: 'done' });
  state = r2.state;
  var all = Sim.query(state, 'boards', null);
  assertEqual(all.length, 2, 'query all returns 2');
  var active = Sim.query(state, 'boards', { status: 'active' });
  assertEqual(active.length, 1, 'query filtered returns 1');
  var none = Sim.query(state, 'nonexistent_collection', {});
  assertEqual(none.length, 0, 'query nonexistent collection returns empty');
})();

// --- Results ---

console.log('\nsim_project_manager Tests: ' + passed + ' passed, ' + failed + ' failed');
if (failed > 0) {
  process.exit(1);
} else {
  console.log('All project_manager simulation tests passed!');
}
