#!/usr/bin/env node
// test_sim_todo.js — Auto-generated tests for sim_todo
// Generated by sim_forge.py
'use strict';

var Sim = require('../src/js/sim_todo.js');

var passed = 0;
var failed = 0;

function assert(condition, message) {
  if (condition) {
    passed++;
  } else {
    failed++;
    console.error('FAIL: ' + message);
  }
}

function assertEqual(actual, expected, message) {
  if (actual === expected) {
    passed++;
  } else {
    failed++;
    console.error('FAIL: ' + message + ' — expected ' + JSON.stringify(expected) + ', got ' + JSON.stringify(actual));
  }
}

// --- initState ---

(function testInitStateEmpty() {
  var state = Sim.initState();
  assert(state && typeof state === 'object', 'initState returns object');
  assert(state._schema && state._schema.collections, 'initState returns state with schema');
  assert(state['items'] && typeof state['items'] === 'object', 'initState returns items object');
})();

(function testInitStateFromSnapshot() {
  var snap = {
    _schema: { collections: {} },
    'items': { 'ite_snap_1': { id: 'ite_snap_1', name: 'Test' } }
  };
  var state = Sim.initState(snap);
  assert(state['items']['ite_snap_1'] !== undefined, 'initState restores snapshot data');
  assertEqual(state['items']['ite_snap_1'].name, 'Test', 'initState restores record name');
  // Deep clone check
  snap['items']['ite_snap_1'].name = 'Modified';
  assertEqual(state['items']['ite_snap_1'].name, 'Test', 'initState deep clones snapshot');
})();

// --- items CRUD ---

(function testCreate_items() {
  var state = Sim.initState();
  var result = Sim.create_items(state, { 'title': 'test_title', 'done': false });
  var record = result.record;
  var newState = result.state;
  assert(record && record.id && record.id.indexOf('ite') === 0, 'create_items id has ite_ prefix');
  assert(newState['items'][record.id] !== undefined, 'create_items stores record');
  assertEqual(Object.keys(state['items']).length, 0, 'create_items does not mutate original state');
})();

(function testUpdate_items() {
  var state = Sim.initState();
  var r = Sim.create_items(state, { name: 'Original' });
  state = r.state;
  var id = r.record.id;
  var updated = Sim.update_items(state, id, { name: 'Updated Name' });
  assertEqual(updated['items'][id].name, 'Updated Name', 'update_items changes name');
  assertEqual(state['items'][id].name, 'Original', 'update_items does not mutate original state');
})();

(function testUpdate_items_missing() {
  var state = Sim.initState();
  var result = Sim.update_items(state, 'nonexistent_id', { name: 'X' });
  assert(result === state, 'update_items nonexistent id returns same state');
})();

(function testDelete_items() {
  var state = Sim.initState();
  var r = Sim.create_items(state, { name: 'Delete me' });
  state = r.state;
  var id = r.record.id;
  var deleted = Sim.delete_items(state, id);
  assert(deleted['items'][id] === undefined, 'delete_items removes record');
  assertEqual(Object.keys(state['items']).length, 1, 'delete_items does not mutate original state');
})();

(function testDelete_items_missing() {
  var state = Sim.initState();
  var result = Sim.delete_items(state, 'nonexistent_id');
  assert(result === state, 'delete_items nonexistent id returns same state');
})();

// --- Schema ---

(function testGetSchema() {
  Sim.initState();
  var schema = Sim.getSchema();
  assert(schema && schema.collections, 'getSchema returns collections');
  assert(schema.collections['items'], 'schema has items collection');
  assert(schema.collections['items'].fields.indexOf('title') !== -1, 'schema items has title field');
  assert(schema.collections['items'].fields.indexOf('done') !== -1, 'schema items has done field');
})();

// --- applyAction ---

(function testApplyAction_create() {
  var state = Sim.initState();
  var msg = {
    from: 'user1',
    payload: {
      action: 'create_items',
      data: { name: 'Action Created' }
    }
  };
  var s2 = Sim.applyAction(state, msg);
  var items = Sim.query(s2, 'items', null);
  assertEqual(items.length, 1, 'applyAction create adds record');
  assertEqual(items[0].name, 'Action Created', 'applyAction create passes name');
  assertEqual(items[0].owner, 'user1', 'applyAction sets owner from msg.from');
})();

(function testApplyAction_update() {
  var state = Sim.initState();
  var r = Sim.create_items(state, { name: 'Before' });
  state = r.state;
  var id = r.record.id;
  var msg = {
    from: 'user1',
    payload: {
      action: 'update_items',
      data: { id: id, name: 'After' }
    }
  };
  var s2 = Sim.applyAction(state, msg);
  assertEqual(s2['items'][id].name, 'After', 'applyAction update changes name');
})();

(function testApplyAction_delete() {
  var state = Sim.initState();
  var r = Sim.create_items(state, { name: 'Gone' });
  state = r.state;
  var id = r.record.id;
  var msg = {
    from: 'user1',
    payload: {
      action: 'delete_items',
      data: { id: id }
    }
  };
  var s2 = Sim.applyAction(state, msg);
  assert(s2['items'][id] === undefined, 'applyAction delete removes record');
})();

(function testApplyAction_unknown() {
  var state = Sim.initState();
  var msg = { from: 'x', payload: { action: 'nonexistent_action_xyz', data: {} } };
  var s2 = Sim.applyAction(state, msg);
  assert(s2 === state, 'applyAction unknown action returns same state');
})();

// --- Edge cases ---

(function testCreate_missing_fields() {
  // Create with no data — should not throw, uses defaults
  var state = Sim.initState();
  var result = Sim.create_items(state, {});
  assert(result && result.record && result.record.id, 'create with empty data sets an id');
})();

(function testUpdate_nonexistent_id() {
  var state = Sim.initState();
  var result = Sim.update_items(state, 'nonexistent', { name: 'X' });
  assert(result === state, 'update nonexistent id returns same state unchanged');
})();

(function testDelete_nonexistent_id() {
  var state = Sim.initState();
  var result = Sim.delete_items(state, 'nonexistent');
  assert(result === state, 'delete nonexistent id returns same state');
})();

// --- Snapshot roundtrip ---

(function testSnapshotRoundtrip() {
  var state = Sim.initState();
  var r_items = Sim.create_items(state, { name: 'Persist items' });
  state = r_items.state;
  var json = JSON.stringify(state);
  var restored = Sim.initState(JSON.parse(json));
  assertEqual(Object.keys(restored['items']).length, 1, 'snapshot restores items');
})();

(function testGetState() {
  var state = Sim.initState();
  var got = Sim.getState();
  assert(got && typeof got === 'object', 'getState returns object');
  assert(got._schema !== undefined, 'getState includes schema');
})();

(function testQuery() {
  var state = Sim.initState();
  var r1 = Sim.create_items(state, { name: 'A', status: 'active' });
  state = r1.state;
  var r2 = Sim.create_items(state, { name: 'B', status: 'done' });
  state = r2.state;
  var all = Sim.query(state, 'items', null);
  assertEqual(all.length, 2, 'query all returns 2');
  var active = Sim.query(state, 'items', { status: 'active' });
  assertEqual(active.length, 1, 'query filtered returns 1');
  var none = Sim.query(state, 'nonexistent_collection', {});
  assertEqual(none.length, 0, 'query nonexistent collection returns empty');
})();

// --- Results ---

console.log('\nsim_todo Tests: ' + passed + ' passed, ' + failed + ' failed');
if (failed > 0) {
  process.exit(1);
} else {
  console.log('All todo simulation tests passed!');
}
