// dashboard_css.js
/**
 * dashboard_css.js - CSS styles for ZION dashboard (UI-only) mode
 *
 * Provides all CSS styles for the dashboard interface, injected
 * dynamically into the document head via a <style> element.
 *
 * UMD module: window.DashboardCSS (browser) or module.exports (Node.js)
 * ES5 compatible - uses var declarations
 */
(function(exports) {
  'use strict';

  // ─── Constants ────────────────────────────────────────────────────────────

  var STYLE_ELEMENT_ID = 'dashboard-styles';

  var BREAKPOINTS = {
    mobile: 768,
    tablet: 1200,
    desktop: 1920
  };

  // ─── CSS Stylesheet ───────────────────────────────────────────────────────

  var LAYOUT_CSS = [
    '/* ═══ ZION Dashboard Layout ═══ */',
    '',
    '/* Dashboard container - replaces 3D canvas */',
    '.dashboard-container {',
    '  display: grid;',
    '  width: 100%;',
    '  height: 100vh;',
    '  grid-template-rows: auto 1fr auto;',
    '  grid-template-areas: "header" "main" "footer";',
    '  background: #0A0E1A;',
    '  color: #E8E0D8;',
    '  font-family: system-ui, -apple-system, sans-serif;',
    '  overflow: hidden;',
    '}',
    '',
    '/* Header bar */',
    '.dashboard-header {',
    '  grid-area: header;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  padding: 8px 16px;',
    '  background: linear-gradient(180deg, rgba(218,165,32,0.15) 0%, rgba(10,14,26,0.95) 100%);',
    '  border-bottom: 1px solid rgba(218,165,32,0.3);',
    '  z-index: 10;',
    '}',
    '',
    '.dashboard-logo {',
    '  font-family: Georgia, "Times New Roman", serif;',
    '  font-size: 1.5rem;',
    '  color: #DAA520;',
    '  letter-spacing: 0.2em;',
    '  font-weight: bold;',
    '}',
    '',
    '.dashboard-player-info {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 16px;',
    '  font-size: 0.9rem;',
    '}',
    '',
    '.dashboard-spark {',
    '  color: #DAA520;',
    '  font-weight: bold;',
    '}',
    '',
    '.dashboard-zone {',
    '  color: #87CEEB;',
    '}',
    '',
    '.dashboard-time {',
    '  color: #A0978E;',
    '}',
    '',
    '/* Main content area with responsive grid */',
    '.dashboard-main {',
    '  grid-area: main;',
    '  display: grid;',
    '  gap: 12px;',
    '  padding: 12px;',
    '  overflow-y: auto;',
    '  grid-template-columns: repeat(3, 1fr);',
    '}',
    '',
    '/* Tablet */',
    '@media (max-width: 1200px) {',
    '  .dashboard-main {',
    '    grid-template-columns: repeat(2, 1fr);',
    '  }',
    '}',
    '',
    '/* Mobile */',
    '@media (max-width: 768px) {',
    '  .dashboard-main {',
    '    grid-template-columns: 1fr;',
    '    padding: 8px;',
    '    gap: 8px;',
    '  }',
    '  .dashboard-header {',
    '    flex-wrap: wrap;',
    '    gap: 8px;',
    '  }',
    '}',
    '',
    '/* Footer navigation tabs */',
    '.dashboard-footer {',
    '  grid-area: footer;',
    '  display: flex;',
    '  justify-content: center;',
    '  gap: 4px;',
    '  padding: 6px 12px;',
    '  background: rgba(10,14,26,0.95);',
    '  border-top: 1px solid rgba(218,165,32,0.2);',
    '}',
    '',
    '.dashboard-tab {',
    '  padding: 8px 16px;',
    '  border: 1px solid transparent;',
    '  border-radius: 4px 4px 0 0;',
    '  background: transparent;',
    '  color: #A0978E;',
    '  cursor: pointer;',
    '  font-size: 0.85rem;',
    '  transition: all 0.2s ease;',
    '}',
    '',
    '.dashboard-tab:hover {',
    '  color: #E8E0D8;',
    '  background: rgba(218,165,32,0.1);',
    '}',
    '',
    '.dashboard-tab.active {',
    '  color: #DAA520;',
    '  border-color: rgba(218,165,32,0.3);',
    '  border-bottom-color: transparent;',
    '  background: rgba(218,165,32,0.1);',
    '}'
  ].join('\n');

  var PANEL_CSS = [
    '/* ═══ Panel Styles ═══ */',
    '',
    '/* Individual panel */',
    '.dashboard-panel {',
    '  background: rgba(15,12,20,0.9);',
    '  border: 1px solid rgba(218,165,32,0.25);',
    '  border-radius: 8px;',
    '  display: flex;',
    '  flex-direction: column;',
    '  max-height: 80vh;',
    '  overflow: hidden;',
    '  transition: border-color 0.2s ease;',
    '}',
    '',
    '.dashboard-panel:hover {',
    '  border-color: rgba(218,165,32,0.5);',
    '}',
    '',
    '.dashboard-panel.focused {',
    '  border-color: #DAA520;',
    '  box-shadow: 0 0 20px rgba(218,165,32,0.15);',
    '}',
    '',
    '.dashboard-panel-header {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  padding: 10px 14px;',
    '  background: rgba(218,165,32,0.08);',
    '  border-bottom: 1px solid rgba(218,165,32,0.15);',
    '  cursor: pointer;',
    '  user-select: none;',
    '}',
    '',
    '.dashboard-panel-title {',
    '  font-family: Georgia, "Times New Roman", serif;',
    '  font-size: 0.95rem;',
    '  color: #DAA520;',
    '  letter-spacing: 0.05em;',
    '}',
    '',
    '.dashboard-panel-controls {',
    '  display: flex;',
    '  gap: 8px;',
    '}',
    '',
    '.dashboard-panel-btn {',
    '  background: none;',
    '  border: none;',
    '  color: #A0978E;',
    '  cursor: pointer;',
    '  font-size: 0.8rem;',
    '  padding: 2px 6px;',
    '  border-radius: 3px;',
    '  transition: color 0.2s ease, background 0.2s ease;',
    '}',
    '',
    '.dashboard-panel-btn:hover {',
    '  color: #DAA520;',
    '  background: rgba(218,165,32,0.15);',
    '}',
    '',
    '.dashboard-panel-body {',
    '  flex: 1;',
    '  padding: 12px 14px;',
    '  overflow-y: auto;',
    '  font-size: 0.85rem;',
    '  line-height: 1.5;',
    '}',
    '',
    '.dashboard-panel.collapsed .dashboard-panel-body {',
    '  display: none;',
    '}',
    '',
    '.dashboard-panel.fullscreen {',
    '  position: fixed;',
    '  top: 0;',
    '  left: 0;',
    '  width: 100%;',
    '  height: 100%;',
    '  max-height: 100vh;',
    '  z-index: 1000;',
    '  border-radius: 0;',
    '  border: none;',
    '}'
  ].join('\n');

  var TABS_CSS = [
    '/* ═══ Tab System (within panels) ═══ */',
    '',
    '.panel-tabs {',
    '  display: flex;',
    '  gap: 2px;',
    '  padding: 0 14px;',
    '  background: rgba(0,0,0,0.2);',
    '  border-bottom: 1px solid rgba(218,165,32,0.1);',
    '}',
    '',
    '.panel-tab {',
    '  padding: 6px 12px;',
    '  border: none;',
    '  background: transparent;',
    '  color: #A0978E;',
    '  cursor: pointer;',
    '  font-size: 0.8rem;',
    '  border-bottom: 2px solid transparent;',
    '  transition: all 0.2s ease;',
    '}',
    '',
    '.panel-tab:hover {',
    '  color: #E8E0D8;',
    '}',
    '',
    '.panel-tab.active {',
    '  color: #DAA520;',
    '  border-bottom-color: #DAA520;',
    '}',
    '',
    '.panel-tab-content {',
    '  display: none;',
    '}',
    '',
    '.panel-tab-content.active {',
    '  display: block;',
    '}'
  ].join('\n');

  var COMMON_CSS = [
    '/* ═══ Common UI Elements ═══ */',
    '',
    '/* Buttons */',
    '.dash-btn {',
    '  padding: 6px 12px;',
    '  border: 1px solid rgba(218,165,32,0.4);',
    '  border-radius: 4px;',
    '  background: rgba(218,165,32,0.1);',
    '  color: #DAA520;',
    '  cursor: pointer;',
    '  font-size: 0.8rem;',
    '  transition: all 0.2s ease;',
    '}',
    '',
    '.dash-btn:hover {',
    '  background: rgba(218,165,32,0.25);',
    '  border-color: #DAA520;',
    '}',
    '',
    '.dash-btn:disabled {',
    '  opacity: 0.4;',
    '  cursor: not-allowed;',
    '}',
    '',
    '.dash-btn-primary {',
    '  background: rgba(218,165,32,0.3);',
    '  border-color: #DAA520;',
    '}',
    '',
    '.dash-btn-danger {',
    '  border-color: rgba(239,83,80,0.5);',
    '  color: #EF5350;',
    '  background: rgba(239,83,80,0.1);',
    '}',
    '',
    '/* Input fields */',
    '.dash-input {',
    '  padding: 6px 10px;',
    '  border: 1px solid rgba(218,165,32,0.25);',
    '  border-radius: 4px;',
    '  background: rgba(0,0,0,0.3);',
    '  color: #E8E0D8;',
    '  font-size: 0.85rem;',
    '  transition: border-color 0.2s ease;',
    '}',
    '',
    '.dash-input:focus {',
    '  outline: none;',
    '  border-color: #DAA520;',
    '}',
    '',
    '.dash-input::placeholder {',
    '  color: #5A5248;',
    '}',
    '',
    '/* Select dropdowns */',
    '.dash-select {',
    '  padding: 6px 10px;',
    '  border: 1px solid rgba(218,165,32,0.25);',
    '  border-radius: 4px;',
    '  background: rgba(0,0,0,0.3);',
    '  color: #E8E0D8;',
    '  font-size: 0.85rem;',
    '}',
    '',
    '/* Progress bars */',
    '.dash-progress {',
    '  height: 6px;',
    '  background: rgba(255,255,255,0.08);',
    '  border-radius: 3px;',
    '  overflow: hidden;',
    '}',
    '',
    '.dash-progress-fill {',
    '  height: 100%;',
    '  border-radius: 3px;',
    '  transition: width 0.3s ease;',
    '}',
    '',
    '.dash-progress-fill.gold { background: linear-gradient(90deg, #DAA520, #F4A460); }',
    '.dash-progress-fill.green { background: linear-gradient(90deg, #4CAF50, #8BC34A); }',
    '.dash-progress-fill.blue { background: linear-gradient(90deg, #2196F3, #03A9F4); }',
    '.dash-progress-fill.red { background: linear-gradient(90deg, #EF5350, #FF7043); }',
    '.dash-progress-fill.purple { background: linear-gradient(90deg, #9C27B0, #BA68C8); }',
    '',
    '/* Rarity borders */',
    '.rarity-common { border-color: #cccccc; }',
    '.rarity-uncommon { border-color: #2ecc71; }',
    '.rarity-rare { border-color: #3498db; }',
    '.rarity-epic { border-color: #9b59b6; }',
    '.rarity-legendary { border-color: #f39c12; }',
    '',
    '/* Item grid */',
    '.item-grid {',
    '  display: grid;',
    '  grid-template-columns: repeat(auto-fill, minmax(80px, 1fr));',
    '  gap: 6px;',
    '}',
    '',
    '.item-slot {',
    '  aspect-ratio: 1;',
    '  border: 1px solid rgba(255,255,255,0.1);',
    '  border-radius: 4px;',
    '  display: flex;',
    '  flex-direction: column;',
    '  align-items: center;',
    '  justify-content: center;',
    '  padding: 4px;',
    '  cursor: pointer;',
    '  transition: all 0.2s ease;',
    '  font-size: 0.75rem;',
    '  position: relative;',
    '}',
    '',
    '.item-slot:hover {',
    '  background: rgba(218,165,32,0.1);',
    '  border-color: rgba(218,165,32,0.4);',
    '}',
    '',
    '.item-slot.selected {',
    '  border-color: #DAA520;',
    '  background: rgba(218,165,32,0.15);',
    '}',
    '',
    '.item-slot .item-count {',
    '  position: absolute;',
    '  bottom: 2px;',
    '  right: 4px;',
    '  font-size: 0.65rem;',
    '  color: #DAA520;',
    '}',
    '',
    '/* List rows */',
    '.dash-row {',
    '  display: flex;',
    '  align-items: center;',
    '  padding: 8px 10px;',
    '  border-bottom: 1px solid rgba(255,255,255,0.05);',
    '  transition: background 0.15s ease;',
    '}',
    '',
    '.dash-row:hover {',
    '  background: rgba(218,165,32,0.05);',
    '}',
    '',
    '.dash-row:last-child {',
    '  border-bottom: none;',
    '}',
    '',
    '/* Badges and tags */',
    '.dash-badge {',
    '  display: inline-block;',
    '  padding: 2px 8px;',
    '  border-radius: 10px;',
    '  font-size: 0.7rem;',
    '  font-weight: 600;',
    '}',
    '',
    '.dash-badge-gold { background: rgba(218,165,32,0.2); color: #DAA520; }',
    '.dash-badge-green { background: rgba(76,175,80,0.2); color: #4CAF50; }',
    '.dash-badge-blue { background: rgba(33,150,243,0.2); color: #2196F3; }',
    '.dash-badge-red { background: rgba(239,83,80,0.2); color: #EF5350; }',
    '.dash-badge-purple { background: rgba(156,39,176,0.2); color: #BA68C8; }',
    '',
    '/* Chat styles */',
    '.chat-message-row {',
    '  padding: 3px 0;',
    '  font-size: 0.82rem;',
    '  line-height: 1.4;',
    '}',
    '',
    '.chat-timestamp {',
    '  color: #5A5248;',
    '  font-size: 0.75rem;',
    '}',
    '',
    '.chat-sender {',
    '  color: #87CEEB;',
    '  font-weight: 600;',
    '}',
    '',
    '.chat-system {',
    '  color: #DAA520;',
    '  font-style: italic;',
    '}',
    '',
    '.chat-whisper {',
    '  color: #BA68C8;',
    '}',
    '',
    '/* ASCII art / game display */',
    '.game-display {',
    '  font-family: "Courier New", monospace;',
    '  background: rgba(0,0,0,0.4);',
    '  border: 1px solid rgba(218,165,32,0.15);',
    '  border-radius: 4px;',
    '  padding: 12px;',
    '  white-space: pre;',
    '  overflow-x: auto;',
    '  font-size: 0.8rem;',
    '  line-height: 1.3;',
    '}',
    '',
    '/* Tooltip */',
    '.dash-tooltip {',
    '  position: absolute;',
    '  background: rgba(10,14,26,0.95);',
    '  border: 1px solid rgba(218,165,32,0.4);',
    '  border-radius: 4px;',
    '  padding: 8px 12px;',
    '  font-size: 0.8rem;',
    '  max-width: 250px;',
    '  z-index: 2000;',
    '  pointer-events: none;',
    '  box-shadow: 0 4px 12px rgba(0,0,0,0.5);',
    '}',
    '',
    '.dash-tooltip-title {',
    '  color: #DAA520;',
    '  font-weight: 600;',
    '  margin-bottom: 4px;',
    '}',
    '',
    '.dash-tooltip-desc {',
    '  color: #A0978E;',
    '  font-size: 0.75rem;',
    '}',
    '',
    '/* Scrollbar styling */',
    '.dashboard-container ::-webkit-scrollbar {',
    '  width: 5px;',
    '}',
    '',
    '.dashboard-container ::-webkit-scrollbar-track {',
    '  background: transparent;',
    '}',
    '',
    '.dashboard-container ::-webkit-scrollbar-thumb {',
    '  background: rgba(218,165,32,0.25);',
    '  border-radius: 3px;',
    '}',
    '',
    '.dashboard-container ::-webkit-scrollbar-thumb:hover {',
    '  background: rgba(218,165,32,0.45);',
    '}',
    '',
    '/* Notification toast for dashboard */',
    '.dash-toast {',
    '  position: fixed;',
    '  top: 60px;',
    '  right: 16px;',
    '  background: rgba(15,12,20,0.95);',
    '  border: 1px solid rgba(218,165,32,0.4);',
    '  border-radius: 6px;',
    '  padding: 12px 16px;',
    '  max-width: 320px;',
    '  z-index: 3000;',
    '  animation: dashToastIn 0.3s ease;',
    '}',
    '',
    '@keyframes dashToastIn {',
    '  from { opacity: 0; transform: translateX(20px); }',
    '  to { opacity: 1; transform: translateX(0); }',
    '}',
    '',
    '/* Loading spinner */',
    '.dash-spinner {',
    '  display: inline-block;',
    '  width: 16px;',
    '  height: 16px;',
    '  border: 2px solid rgba(218,165,32,0.2);',
    '  border-top-color: #DAA520;',
    '  border-radius: 50%;',
    '  animation: dashSpin 0.8s linear infinite;',
    '}',
    '',
    '@keyframes dashSpin {',
    '  to { transform: rotate(360deg); }',
    '}',
    '',
    '/* Empty state */',
    '.dash-empty {',
    '  text-align: center;',
    '  padding: 24px;',
    '  color: #5A5248;',
    '  font-style: italic;',
    '}',
    '',
    '/* Divider */',
    '.dash-divider {',
    '  height: 1px;',
    '  background: rgba(218,165,32,0.15);',
    '  margin: 8px 0;',
    '}',
    '',
    '/* Zone colors for badges */',
    '.zone-nexus { border-left: 3px solid #8888cc; }',
    '.zone-gardens { border-left: 3px solid #4caf50; }',
    '.zone-athenaeum { border-left: 3px solid #795548; }',
    '.zone-studio { border-left: 3px solid #ff9800; }',
    '.zone-wilds { border-left: 3px solid #2e7d32; }',
    '.zone-agora { border-left: 3px solid #ffd700; }',
    '.zone-commons { border-left: 3px solid #faf0e6; }',
    '.zone-arena { border-left: 3px solid #d2691e; }'
  ].join('\n');

  var ANIMATION_CSS = [
    '/* ═══ Animation States ═══ */',
    '',
    '/* Panel transitions */',
    '.dashboard-panel-enter {',
    '  animation: panelFadeIn 0.3s ease;',
    '}',
    '',
    '@keyframes panelFadeIn {',
    '  from { opacity: 0; transform: translateY(10px); }',
    '  to { opacity: 1; transform: translateY(0); }',
    '}',
    '',
    '.dashboard-panel-exit {',
    '  animation: panelFadeOut 0.2s ease;',
    '}',
    '',
    '@keyframes panelFadeOut {',
    '  from { opacity: 1; }',
    '  to { opacity: 0; transform: translateY(-10px); }',
    '}',
    '',
    '/* Zone transition text */',
    '.zone-transition-overlay {',
    '  position: fixed;',
    '  top: 0;',
    '  left: 0;',
    '  right: 0;',
    '  bottom: 0;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  background: rgba(10,14,26,0.8);',
    '  z-index: 5000;',
    '  animation: zoneFade 1.5s ease-in-out;',
    '}',
    '',
    '@keyframes zoneFade {',
    '  0% { opacity: 0; }',
    '  30% { opacity: 1; }',
    '  70% { opacity: 1; }',
    '  100% { opacity: 0; }',
    '}'
  ].join('\n');

  // ─── Full Stylesheet ───────────────────────────────────────────────────────

  /**
   * Returns the complete CSS string.
   * Safe to call in Node.js (no DOM required).
   * @returns {string}
   */
  function getStylesheet() {
    return [
      LAYOUT_CSS,
      '',
      PANEL_CSS,
      '',
      TABS_CSS,
      '',
      COMMON_CSS,
      '',
      ANIMATION_CSS
    ].join('\n');
  }

  /**
   * Returns responsive breakpoint pixel values.
   * @returns {{ mobile: number, tablet: number, desktop: number }}
   */
  function getBreakpoints() {
    return {
      mobile: BREAKPOINTS.mobile,
      tablet: BREAKPOINTS.tablet,
      desktop: BREAKPOINTS.desktop
    };
  }

  /**
   * Injects all dashboard CSS into the document head.
   * Idempotent — does nothing if styles are already injected.
   * @returns {HTMLStyleElement} the style element
   */
  function injectStyles() {
    if (typeof document === 'undefined') {
      throw new Error('injectStyles() requires a DOM environment');
    }

    var existing = document.getElementById(STYLE_ELEMENT_ID);
    if (existing) {
      return existing;
    }

    var style = document.createElement('style');
    style.id = STYLE_ELEMENT_ID;
    style.textContent = getStylesheet();
    document.head.appendChild(style);
    return style;
  }

  /**
   * Removes the injected dashboard style element (if present).
   */
  function removeStyles() {
    if (typeof document === 'undefined') {
      return;
    }
    var el = document.getElementById(STYLE_ELEMENT_ID);
    if (el && el.parentNode) {
      el.parentNode.removeChild(el);
    }
  }

  // ─── Exports ──────────────────────────────────────────────────────────────

  exports.injectStyles = injectStyles;
  exports.removeStyles = removeStyles;
  exports.getStylesheet = getStylesheet;
  exports.getBreakpoints = getBreakpoints;

  // Internal constants exposed for testing
  exports.STYLE_ELEMENT_ID = STYLE_ELEMENT_ID;

})(typeof module !== 'undefined' ? module.exports : (window.DashboardCSS = {}));
