// sim_forge_browser.js — Simulation Forge for ZION (browser port of sim_forge.py)
// Article XI: Simulations run locally, store state as JSON, use pure functions.
// Ported from scripts/sim_forge.py — generates UMD JS simulation modules in-browser.
(function(exports) {
  'use strict';

  // ---------------------------------------------------------------------------
  // Internal helpers (mirror Python helper functions)
  // ---------------------------------------------------------------------------

  function _jsStr(s) {
    // Escape a string as a JS single-quoted string literal
    return "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
  }

  function _collPrefix(collName) {
    // Derive a 3-char prefix for IDs from a collection name
    return collName.slice(0, 3).toLowerCase();
  }

  function _pascal(s) {
    // Convert snake_case to PascalCase
    return s.split('_').map(function(part) {
      return part.charAt(0).toUpperCase() + part.slice(1);
    }).join('');
  }

  function _windowName(simName) {
    return 'Sim' + _pascal(simName);
  }

  function _moduleName(simName) {
    return 'sim_' + simName;
  }

  // Deep clone via JSON round-trip
  function _deepClone(obj) {
    return JSON.parse(JSON.stringify(obj));
  }

  // Check if a value is a plain object (not array, not null)
  function _isPlainObject(v) {
    return v !== null && typeof v === 'object' && !Array.isArray(v);
  }

  // ---------------------------------------------------------------------------
  // parseSpec — validate and apply defaults (mirrors parse_spec)
  // ---------------------------------------------------------------------------

  function parseSpec(specInput) {
    var spec;
    if (typeof specInput === 'string') {
      try {
        spec = JSON.parse(specInput);
      } catch (e) {
        throw new Error('Invalid JSON in spec: ' + e.message);
      }
    } else if (_isPlainObject(specInput)) {
      // Deep copy to avoid mutating the input
      spec = _deepClone(specInput);
    } else {
      throw new Error('spec_input must be an object or JSON string');
    }

    // --- Validate name ---
    if (!spec.name) {
      throw new Error('Spec must have a non-empty "name" field');
    }
    var name = spec.name;
    if (typeof name !== 'string') {
      throw new Error('"name" must be a string');
    }
    if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
      throw new Error(
        '"name" must start with a letter or underscore and contain only ' +
        'alphanumeric characters and underscores, got: ' + JSON.stringify(name)
      );
    }

    // --- Validate collections ---
    if (!spec.collections) {
      throw new Error('Spec must have a "collections" field');
    }
    var collections = spec.collections;
    if (!_isPlainObject(collections)) {
      throw new Error('"collections" must be an object/dict');
    }
    var collKeys = Object.keys(collections);
    if (collKeys.length === 0) {
      throw new Error('"collections" must have at least one collection');
    }

    // Normalise each collection entry
    for (var i = 0; i < collKeys.length; i++) {
      var collName = collKeys[i];
      var collDef = collections[collName];
      if (!_isPlainObject(collDef)) {
        collections[collName] = { fields: [] };
        collDef = collections[collName];
      }
      if (!collDef.fields || collDef.fields === null) {
        collDef.fields = [];
      }
      if (!Array.isArray(collDef.fields)) {
        throw new Error('fields for collection "' + collName + '" must be a list');
      }
    }

    // --- Default actions ---
    if (!spec.actions || spec.actions.length === 0) {
      spec.actions = ['create', 'update', 'delete'];
    }

    // --- Default description ---
    if (!spec.description) {
      spec.description = 'A ' + name.replace(/_/g, ' ') + ' simulation';
    }

    return spec;
  }

  // ---------------------------------------------------------------------------
  // generateModule — produce a UMD JS simulation module source string
  // ---------------------------------------------------------------------------

  function generateModule(spec) {
    var name = spec.name;
    var collections = spec.collections;
    var description = spec.description || '';
    var windowName = _windowName(name);
    var collNames = Object.keys(collections);

    var lines = [];
    function w(line) { lines.push(line); }

    // Header
    w('// sim_' + name + '.js — ' + description);
    w('// Auto-generated by sim_forge.py — Article XI: Simulations');
    w('// initState(snapshot), applyAction(state, message), getState(), getSchema()');
    w('(function(exports) {');
    w("  'use strict';");
    w('');

    // Schema definition
    w('  // --- Schema ---');
    w('');
    w('  var _schema = {');
    w('    collections: {');
    for (var si = 0; si < collNames.length; si++) {
      var collName = collNames[si];
      var collDef = collections[collName];
      var fields = collDef.fields || [];
      var prefix = _collPrefix(collName);
      var fieldsJs = '[' + fields.map(_jsStr).join(', ') + ']';
      var comma = (si < collNames.length - 1) ? ',' : '';
      w('      ' + _jsStr(collName) + ': { prefix: ' + _jsStr(prefix) + ', fields: ' + fieldsJs + ' }' + comma);
    }
    w('    }');
    w('  };');
    w('');

    // State holder
    w('  var _state = null;');
    w('  var _idCounter = 0;');
    w('');

    // Utility functions
    w('  // --- Utilities ---');
    w('');
    w('  function clone(obj) {');
    w('    return JSON.parse(JSON.stringify(obj));');
    w('  }');
    w('');
    w('  function generateId(prefix) {');
    w('    _idCounter++;');
    w("    return prefix + '_' + Date.now().toString(36) + '_' + _idCounter;");
    w('  }');
    w('');
    w('  function objectKeys(obj) {');
    w('    var keys = [];');
    w('    for (var k in obj) {');
    w('      if (obj.hasOwnProperty(k)) { keys.push(k); }');
    w('    }');
    w('    return keys;');
    w('  }');
    w('');
    w('  function mergeOwner(data, from) {');
    w('    var out = {};');
    w('    for (var k in data) {');
    w('      if (data.hasOwnProperty(k)) { out[k] = data[k]; }');
    w('    }');
    w("    if (!out.owner) { out.owner = from || 'system'; }");
    w('    return out;');
    w('  }');
    w('');

    // initState
    w('  // --- State Management ---');
    w('');
    w('  function initState(snapshot) {');
    w('    var freshSchema = JSON.parse(JSON.stringify(_schema));');
    w("    if (snapshot && typeof snapshot === 'object') {");
    w('      // Restore id counter from existing records');
    w('      var maxNum = 0;');
    w('      var collNames = objectKeys((snapshot._schema || {}).collections || {});');

    // Also scan the spec collections (same as Python: extra_colls)
    var extraColls = '[' + collNames.map(_jsStr).join(', ') + ']';
    w('      var specColls = ' + extraColls + ';');
    w('      for (var si = 0; si < specColls.length; si++) {');
    w('        if (collNames.indexOf(specColls[si]) === -1) { collNames.push(specColls[si]); }');
    w('      }');
    w('      for (var ci = 0; ci < collNames.length; ci++) {');
    w("        var coll = snapshot[collNames[ci]];");
    w("        if (coll && typeof coll === 'object' && !Array.isArray(coll)) {");
    w('          var ids = objectKeys(coll);');
    w('          for (var ii = 0; ii < ids.length; ii++) {');
    w("            var parts = ids[ii].split('_');");
    w('            var num = parseInt(parts[parts.length - 1], 10);');
    w('            if (!isNaN(num) && num > maxNum) { maxNum = num; }');
    w('          }');
    w('        }');
    w('      }');
    w('      _idCounter = maxNum;');
    w('      var loaded = clone(snapshot);');
    w('      if (!loaded._schema) { loaded._schema = freshSchema; }');
    w('      // Ensure all spec collections exist');
    w('      for (var sci = 0; sci < specColls.length; sci++) {');
    w('        if (!loaded[specColls[sci]]) { loaded[specColls[sci]] = {}; }');
    w('      }');
    w('      _state = loaded;');
    w('      return _state;');
    w('    }');
    w('    // Fresh state');
    w('    _idCounter = 0;');
    w('    _state = {');
    w('      _schema: freshSchema,');
    w('      _sim: ' + _jsStr(name) + ',');
    w('      _created_at: new Date().toISOString()');
    w('    };');
    for (var ci2 = 0; ci2 < collNames.length; ci2++) {
      w('    _state[' + _jsStr(collNames[ci2]) + '] = {};');
    }
    w('    return _state;');
    w('  }');
    w('');

    // CRUD helpers per collection
    w('  // --- CRUD Helpers ---');
    w('');
    for (var cri = 0; cri < collNames.length; cri++) {
      var cName = collNames[cri];
      var cDef = collections[cName];
      var cFields = cDef.fields || [];
      var cPrefix = _collPrefix(cName);

      // createItem
      w('  function create_' + cName + '(state, data) {');
      w('    var s = clone(state);');
      w('    var id = generateId(' + _jsStr(cPrefix) + ');');
      w('    var record = {');
      w('      id: id,');
      w("      owner: data.owner || 'system',");
      w('      createdAt: new Date().toISOString()');
      w('    };');
      w('    for (var k in data) {');
      w('      if (data.hasOwnProperty(k)) { record[k] = data[k]; }');
      w('    }');
      w("    if (!record.name && !record.title) {");
      // Mirror Python: coll_name.rstrip('s') removes trailing 's'
      var singularName = cName.replace(/s$/, '');
      w("      record.name = 'Unnamed " + singularName + "';");
      w('    }');
      w('    s[' + _jsStr(cName) + '][id] = record;');
      w('    return { state: s, record: record };');
      w('  }');
      w('');

      // updateItem
      w('  function update_' + cName + '(state, id, data) {');
      w('    if (!state[' + _jsStr(cName) + '] || !state[' + _jsStr(cName) + '][id]) { return state; }');
      w('    var s = clone(state);');
      w('    var target = s[' + _jsStr(cName) + '][id];');
      w('    for (var k in data) {');
      w("      if (data.hasOwnProperty(k) && k !== 'id') { target[k] = data[k]; }");
      w('    }');
      w('    target.updatedAt = new Date().toISOString();');
      w('    return s;');
      w('  }');
      w('');

      // deleteItem
      w('  function delete_' + cName + '(state, id) {');
      w('    if (!state[' + _jsStr(cName) + '] || !state[' + _jsStr(cName) + '][id]) { return state; }');
      w('    var s = clone(state);');
      w('    delete s[' + _jsStr(cName) + '][id];');
      w('    return s;');
      w('  }');
      w('');
    }

    // applyAction dispatch
    w('  // --- Action Dispatch ---');
    w('');
    w('  function applyAction(state, msg) {');
    w("    var payload = (msg && msg.payload) ? msg.payload : (msg || {});");
    w("    var action = payload.action || '';");
    w('    var data = payload.data || {};');
    w("    var from = (msg && msg.from) || payload.from || 'system';");
    w('    var result;');
    w('');
    w('    if (!state || !state._schema) {');
    w('      state = initState(state);');
    w('    }');
    w('');
    w('    switch (action) {');

    for (var ai = 0; ai < collNames.length; ai++) {
      var aColl = collNames[ai];
      // create_<coll>
      w('      case ' + _jsStr('create_' + aColl) + ':');
      w('        result = create_' + aColl + '(state, mergeOwner(data, from));');
      w('        return result.state;');
      w('');
      // update_<coll>
      w('      case ' + _jsStr('update_' + aColl) + ':');
      w('        return update_' + aColl + '(state, data.id, data);');
      w('');
      // delete_<coll>
      w('      case ' + _jsStr('delete_' + aColl) + ':');
      w('        return delete_' + aColl + '(state, data.id);');
      w('');
    }

    // Handle custom actions from spec
    var actions = spec.actions || [];
    var customActions = actions.filter(function(a) {
      return a !== 'create' && a !== 'update' && a !== 'delete';
    });

    for (var cai = 0; cai < customActions.length; cai++) {
      var action = customActions[cai];

      if (action === 'complete') {
        for (var ci3 = 0; ci3 < collNames.length; ci3++) {
          var ccName = collNames[ci3];
          var ccFields = collections[ccName].fields || [];
          var caseName = 'complete_' + ccName;
          w('      case ' + _jsStr(caseName) + ':');
          w('        var sc = clone(state);');
          w('        if (sc[' + _jsStr(ccName) + '] && sc[' + _jsStr(ccName) + '][data.id]) {');
          if (ccFields.indexOf('done') !== -1) {
            w('          sc[' + _jsStr(ccName) + '][data.id].done = true;');
          }
          if (ccFields.indexOf('status') !== -1) {
            w("          sc[" + _jsStr(ccName) + "][data.id].status = 'completed';");
          }
          w('          sc[' + _jsStr(ccName) + '][data.id].completedAt = new Date().toISOString();');
          w('        }');
          w('        return sc;');
          w('');
        }
      } else if (action === 'assign') {
        for (var ci4 = 0; ci4 < collNames.length; ci4++) {
          var acName = collNames[ci4];
          var acFields = collections[acName].fields || [];
          if (acFields.indexOf('assignee') !== -1) {
            var acaseName = 'assign_' + acName;
            w('      case ' + _jsStr(acaseName) + ':');
            w('        var sa = clone(state);');
            w('        if (sa[' + _jsStr(acName) + '] && sa[' + _jsStr(acName) + '][data.id]) {');
            w('          sa[' + _jsStr(acName) + '][data.id].assignee = data.assignee || from;');
            w('          sa[' + _jsStr(acName) + '][data.id].updatedAt = new Date().toISOString();');
            w('        }');
            w('        return sa;');
            w('');
          }
        }
      } else if (action === 'move') {
        for (var ci5 = 0; ci5 < collNames.length; ci5++) {
          var mcName = collNames[ci5];
          var mcFields = collections[mcName].fields || [];
          var hasBoard = mcFields.indexOf('board_id') !== -1;
          var hasParent = mcFields.indexOf('parent_id') !== -1;
          if (hasBoard || hasParent) {
            var targetField = hasBoard ? 'board_id' : 'parent_id';
            var mcaseName = 'move_' + mcName;
            w('      case ' + _jsStr(mcaseName) + ':');
            w('        var sm = clone(state);');
            w('        if (sm[' + _jsStr(mcName) + '] && sm[' + _jsStr(mcName) + '][data.id]) {');
            w('          sm[' + _jsStr(mcName) + '][data.id][' + _jsStr(targetField) + '] = data.' + targetField + ';');
            w('          sm[' + _jsStr(mcName) + '][data.id].updatedAt = new Date().toISOString();');
            w('        }');
            w('        return sm;');
            w('');
          }
        }
      }
    }

    // default: unknown action returns same state
    w('      default:');
    w('        return state;');
    w('    }');
    w('  }');
    w('');

    // query helper
    w('  // --- Query ---');
    w('');
    w('  function query(state, collName, filter) {');
    w("    var coll = state[collName];");
    w("    if (!coll || typeof coll !== 'object' || Array.isArray(coll)) { return []; }");
    w('    var results = [];');
    w('    var ids = objectKeys(coll);');
    w('    for (var i = 0; i < ids.length; i++) {');
    w('      var item = coll[ids[i]];');
    w('      if (!filter || matchesFilter(item, filter)) {');
    w('        results.push(item);');
    w('      }');
    w('    }');
    w('    return results;');
    w('  }');
    w('');
    w('  function matchesFilter(item, filter) {');
    w('    for (var k in filter) {');
    w('      if (filter.hasOwnProperty(k)) {');
    w('        if (item[k] !== filter[k]) { return false; }');
    w('      }');
    w('    }');
    w('    return true;');
    w('  }');
    w('');

    // Public exports
    w('  // --- Public API ---');
    w('');
    w('  exports.initState = function(snapshot) {');
    w('    return initState(snapshot);');
    w('  };');
    w('');
    w('  exports.applyAction = function(state, msg) {');
    w('    return applyAction(state, msg);');
    w('  };');
    w('');
    w('  exports.getState = function() {');
    w('    return JSON.parse(JSON.stringify(_state));');
    w('  };');
    w('');
    w('  exports.getSchema = function() {');
    w('    return JSON.parse(JSON.stringify(_schema));');
    w('  };');
    w('');
    w('  exports.query = function(state, collName, filter) {');
    w('    return query(state, collName, filter);');
    w('  };');
    w('');

    // Also export individual CRUD functions for direct use in tests
    for (var ei = 0; ei < collNames.length; ei++) {
      var eName = collNames[ei];
      w('  exports.create_' + eName + ' = function(state, data) {');
      w('    return create_' + eName + '(state, data);');
      w('  };');
      w('  exports.update_' + eName + ' = function(state, id, data) {');
      w('    return update_' + eName + '(state, id, data);');
      w('  };');
      w('  exports.delete_' + eName + ' = function(state, id) {');
      w('    return delete_' + eName + '(state, id);');
      w('  };');
      w('');
    }

    // UMD footer
    w("})(typeof module !== 'undefined' ? module.exports : (window." + windowName + " = {}));");

    return lines.join('\n') + '\n';
  }

  // ---------------------------------------------------------------------------
  // generateState — produce initial state JSON object (mirrors generate_state)
  // ---------------------------------------------------------------------------

  function generateState(spec) {
    var name = spec.name;
    var collections = spec.collections;
    var collNames = Object.keys(collections);

    var schemaCollections = {};
    for (var i = 0; i < collNames.length; i++) {
      var collName = collNames[i];
      var collDef = collections[collName];
      var fields = collDef.fields || [];
      schemaCollections[collName] = {
        prefix: _collPrefix(collName),
        fields: fields.slice()
      };
    }

    var state = {
      _sim: name,
      _schema: {
        collections: schemaCollections
      },
      _created_at: new Date().toISOString()
    };

    // Empty collections
    for (var j = 0; j < collNames.length; j++) {
      state[collNames[j]] = {};
    }

    return state;
  }

  // ---------------------------------------------------------------------------
  // generateTests — produce a JS test source string (mirrors generate_tests)
  // ---------------------------------------------------------------------------

  function generateTests(spec) {
    var name = spec.name;
    var collections = spec.collections;
    var collNames = Object.keys(collections);
    var moduleName = _moduleName(name);
    var moduleVar = 'Sim';

    var lines = [];
    function w(line) { lines.push(line); }

    w('#!/usr/bin/env node');
    w('// test_sim_' + name + '.js — Auto-generated tests for ' + moduleName);
    w('// Generated by sim_forge.py');
    w("'use strict';");
    w('');
    w('var ' + moduleVar + " = require('../src/js/" + moduleName + ".js');");
    w('');
    w('var passed = 0;');
    w('var failed = 0;');
    w('');
    w('function assert(condition, message) {');
    w('  if (condition) {');
    w('    passed++;');
    w('  } else {');
    w('    failed++;');
    w("    console.error('FAIL: ' + message);");
    w('  }');
    w('}');
    w('');
    w('function assertEqual(actual, expected, message) {');
    w('  if (actual === expected) {');
    w('    passed++;');
    w('  } else {');
    w('    failed++;');
    w("    console.error('FAIL: ' + message + ' — expected ' + JSON.stringify(expected) + ', got ' + JSON.stringify(actual));");
    w('  }');
    w('}');
    w('');

    // --- initState tests ---
    w('// --- initState ---');
    w('');
    w('(function testInitStateEmpty() {');
    w('  var state = ' + moduleVar + '.initState();');
    w("  assert(state && typeof state === 'object', 'initState returns object');");
    w("  assert(state._schema && state._schema.collections, 'initState returns state with schema');");
    for (var ici = 0; ici < collNames.length; ici++) {
      var icName = collNames[ici];
      w("  assert(state[" + _jsStr(icName) + "] && typeof state[" + _jsStr(icName) + "] === 'object', 'initState returns " + icName + " object');");
    }
    w('})();');
    w('');

    w('(function testInitStateFromSnapshot() {');
    var firstColl = collNames[0];
    var firstPrefix = _collPrefix(firstColl);
    var testId = firstPrefix + '_snap_1';
    w('  var snap = {');
    w('    _schema: { collections: {} },');
    for (var sni = 0; sni < collNames.length; sni++) {
      var snName = collNames[sni];
      var snComma = (sni < collNames.length - 1) ? ',' : '';
      if (sni === 0) {
        w('    ' + _jsStr(snName) + ': { ' + _jsStr(testId) + ': { id: ' + _jsStr(testId) + ", name: 'Test' } }" + snComma);
      } else {
        w('    ' + _jsStr(snName) + ': {}' + snComma);
      }
    }
    w('  };');
    w('  var state = ' + moduleVar + '.initState(snap);');
    w("  assert(state[" + _jsStr(firstColl) + "][" + _jsStr(testId) + "] !== undefined, 'initState restores snapshot data');");
    w("  assertEqual(state[" + _jsStr(firstColl) + "][" + _jsStr(testId) + "].name, 'Test', 'initState restores record name');");
    w('  // Deep clone check');
    w("  snap[" + _jsStr(firstColl) + "][" + _jsStr(testId) + "].name = 'Modified';");
    w("  assertEqual(state[" + _jsStr(firstColl) + "][" + _jsStr(testId) + "].name, 'Test', 'initState deep clones snapshot');");
    w('})();');
    w('');

    // --- CRUD tests per collection ---
    for (var tci = 0; tci < collNames.length; tci++) {
      var tcName = collNames[tci];
      var tcDef = collections[tcName];
      var tcFields = tcDef.fields || [];
      var tcPrefix = _collPrefix(tcName);

      w('// --- ' + tcName + ' CRUD ---');
      w('');

      // Create
      w('(function testCreate_' + tcName + '() {');
      w('  var state = ' + moduleVar + '.initState();');
      // Build a data object from fields (take first 3)
      var testDataParts = [];
      for (var fi = 0; fi < Math.min(tcFields.length, 3); fi++) {
        var f = tcFields[fi];
        if (f === 'done') {
          testDataParts.push(_jsStr(f) + ': false');
        } else if (f === 'status') {
          testDataParts.push(_jsStr(f) + ": 'active'");
        } else if (f === 'priority') {
          testDataParts.push(_jsStr(f) + ": 'high'");
        } else {
          testDataParts.push(_jsStr(f) + ': ' + _jsStr('test_' + f));
        }
      }
      var testData = testDataParts.length > 0
        ? '{ ' + testDataParts.join(', ') + ' }'
        : "{ name: 'Test Item' }";
      w('  var result = ' + moduleVar + '.create_' + tcName + '(state, ' + testData + ');');
      w('  var record = result.record;');
      w('  var newState = result.state;');
      w("  assert(record && record.id && record.id.indexOf(" + _jsStr(tcPrefix) + ") === 0, 'create_" + tcName + " id has " + tcPrefix + "_ prefix');");
      w("  assert(newState[" + _jsStr(tcName) + "][record.id] !== undefined, 'create_" + tcName + " stores record');");
      w("  assertEqual(Object.keys(state[" + _jsStr(tcName) + "]).length, 0, 'create_" + tcName + " does not mutate original state');");
      w('})();');
      w('');

      // Update
      w('(function testUpdate_' + tcName + '() {');
      w('  var state = ' + moduleVar + '.initState();');
      w("  var r = " + moduleVar + ".create_" + tcName + "(state, { name: 'Original' });");
      w('  state = r.state;');
      w('  var id = r.record.id;');
      w("  var updated = " + moduleVar + ".update_" + tcName + "(state, id, { name: 'Updated Name' });");
      w("  assertEqual(updated[" + _jsStr(tcName) + "][id].name, 'Updated Name', 'update_" + tcName + " changes name');");
      w("  assertEqual(state[" + _jsStr(tcName) + "][id].name, 'Original', 'update_" + tcName + " does not mutate original state');");
      w('})();');
      w('');

      // Update missing (edge case)
      w('(function testUpdate_' + tcName + '_missing() {');
      w('  var state = ' + moduleVar + '.initState();');
      w("  var result = " + moduleVar + ".update_" + tcName + "(state, 'nonexistent_id', { name: 'X' });");
      w("  assert(result === state, 'update_" + tcName + " nonexistent id returns same state');");
      w('})();');
      w('');

      // Delete
      w('(function testDelete_' + tcName + '() {');
      w('  var state = ' + moduleVar + '.initState();');
      w("  var r = " + moduleVar + ".create_" + tcName + "(state, { name: 'Delete me' });");
      w('  state = r.state;');
      w('  var id = r.record.id;');
      w('  var deleted = ' + moduleVar + '.delete_' + tcName + '(state, id);');
      w("  assert(deleted[" + _jsStr(tcName) + "][id] === undefined, 'delete_" + tcName + " removes record');");
      w("  assertEqual(Object.keys(state[" + _jsStr(tcName) + "]).length, 1, 'delete_" + tcName + " does not mutate original state');");
      w('})();');
      w('');

      // Delete missing (edge case)
      w('(function testDelete_' + tcName + '_missing() {');
      w('  var state = ' + moduleVar + '.initState();');
      w("  var result = " + moduleVar + ".delete_" + tcName + "(state, 'nonexistent_id');");
      w("  assert(result === state, 'delete_" + tcName + " nonexistent id returns same state');");
      w('})();');
      w('');
    }

    // --- Schema validation ---
    w('// --- Schema ---');
    w('');
    w('(function testGetSchema() {');
    w('  ' + moduleVar + '.initState();');
    w('  var schema = ' + moduleVar + '.getSchema();');
    w("  assert(schema && schema.collections, 'getSchema returns collections');");
    for (var sci = 0; sci < collNames.length; sci++) {
      var scName = collNames[sci];
      w("  assert(schema.collections[" + _jsStr(scName) + "], 'schema has " + scName + " collection');");
      var scFields = collections[scName].fields || [];
      for (var sfi = 0; sfi < Math.min(scFields.length, 2); sfi++) {
        w("  assert(schema.collections[" + _jsStr(scName) + "].fields.indexOf(" + _jsStr(scFields[sfi]) + ") !== -1, 'schema " + scName + " has " + scFields[sfi] + " field');");
      }
    }
    w('})();');
    w('');

    // --- applyAction tests ---
    w('// --- applyAction ---');
    w('');
    w('(function testApplyAction_create() {');
    w('  var state = ' + moduleVar + '.initState();');
    w('  var msg = {');
    w("    from: 'user1',");
    w('    payload: {');
    w('      action: ' + _jsStr('create_' + firstColl) + ',');
    w("      data: { name: 'Action Created' }");
    w('    }');
    w('  };');
    w('  var s2 = ' + moduleVar + '.applyAction(state, msg);');
    w('  var items = ' + moduleVar + '.query(s2, ' + _jsStr(firstColl) + ', null);');
    w("  assertEqual(items.length, 1, 'applyAction create adds record');");
    w("  assertEqual(items[0].name, 'Action Created', 'applyAction create passes name');");
    w("  assertEqual(items[0].owner, 'user1', 'applyAction sets owner from msg.from');");
    w('})();');
    w('');

    w('(function testApplyAction_update() {');
    w('  var state = ' + moduleVar + '.initState();');
    w("  var r = " + moduleVar + ".create_" + firstColl + "(state, { name: 'Before' });");
    w('  state = r.state;');
    w('  var id = r.record.id;');
    w('  var msg = {');
    w("    from: 'user1',");
    w('    payload: {');
    w('      action: ' + _jsStr('update_' + firstColl) + ',');
    w("      data: { id: id, name: 'After' }");
    w('    }');
    w('  };');
    w('  var s2 = ' + moduleVar + '.applyAction(state, msg);');
    w("  assertEqual(s2[" + _jsStr(firstColl) + "][id].name, 'After', 'applyAction update changes name');");
    w('})();');
    w('');

    w('(function testApplyAction_delete() {');
    w('  var state = ' + moduleVar + '.initState();');
    w("  var r = " + moduleVar + ".create_" + firstColl + "(state, { name: 'Gone' });");
    w('  state = r.state;');
    w('  var id = r.record.id;');
    w('  var msg = {');
    w("    from: 'user1',");
    w('    payload: {');
    w('      action: ' + _jsStr('delete_' + firstColl) + ',');
    w('      data: { id: id }');
    w('    }');
    w('  };');
    w('  var s2 = ' + moduleVar + '.applyAction(state, msg);');
    w("  assert(s2[" + _jsStr(firstColl) + "][id] === undefined, 'applyAction delete removes record');");
    w('})();');
    w('');

    w('(function testApplyAction_unknown() {');
    w('  var state = ' + moduleVar + '.initState();');
    w("  var msg = { from: 'x', payload: { action: 'nonexistent_action_xyz', data: {} } };");
    w('  var s2 = ' + moduleVar + '.applyAction(state, msg);');
    w("  assert(s2 === state, 'applyAction unknown action returns same state');");
    w('})();');
    w('');

    // --- Edge cases ---
    w('// --- Edge cases ---');
    w('');

    w('(function testCreate_missing_fields() {');
    w('  // Create with no data — should not throw, uses defaults');
    w('  var state = ' + moduleVar + '.initState();');
    w('  var result = ' + moduleVar + '.create_' + firstColl + '(state, {});');
    w("  assert(result && result.record && result.record.id, 'create with empty data sets an id');");
    w('})();');
    w('');

    w('(function testUpdate_nonexistent_id() {');
    w('  var state = ' + moduleVar + '.initState();');
    w("  var result = " + moduleVar + ".update_" + firstColl + "(state, 'nonexistent', { name: 'X' });");
    w("  assert(result === state, 'update nonexistent id returns same state unchanged');");
    w('})();');
    w('');

    w('(function testDelete_nonexistent_id() {');
    w('  var state = ' + moduleVar + '.initState();');
    w("  var result = " + moduleVar + ".delete_" + firstColl + "(state, 'nonexistent');");
    w("  assert(result === state, 'delete nonexistent id returns same state');");
    w('})();');
    w('');

    // --- Snapshot roundtrip ---
    w('// --- Snapshot roundtrip ---');
    w('');
    w('(function testSnapshotRoundtrip() {');
    w('  var state = ' + moduleVar + '.initState();');
    for (var sri = 0; sri < collNames.length; sri++) {
      var srName = collNames[sri];
      var srVar = 'r_' + srName;
      w("  var " + srVar + " = " + moduleVar + ".create_" + srName + "(state, { name: 'Persist " + srName + "' });");
      w('  state = ' + srVar + '.state;');
    }
    w('  var json = JSON.stringify(state);');
    w('  var restored = ' + moduleVar + '.initState(JSON.parse(json));');
    for (var srrI = 0; srrI < collNames.length; srrI++) {
      var srrName = collNames[srrI];
      w("  assertEqual(Object.keys(restored[" + _jsStr(srrName) + "]).length, 1, 'snapshot restores " + srrName + "');");
    }
    w('})();');
    w('');

    // --- getState ---
    w('(function testGetState() {');
    w('  var state = ' + moduleVar + '.initState();');
    w('  var got = ' + moduleVar + '.getState();');
    w("  assert(got && typeof got === 'object', 'getState returns object');");
    w("  assert(got._schema !== undefined, 'getState includes schema');");
    w('})();');
    w('');

    // --- query ---
    w('(function testQuery() {');
    w('  var state = ' + moduleVar + '.initState();');
    w("  var r1 = " + moduleVar + ".create_" + firstColl + "(state, { name: 'A', status: 'active' });");
    w('  state = r1.state;');
    w("  var r2 = " + moduleVar + ".create_" + firstColl + "(state, { name: 'B', status: 'done' });");
    w('  state = r2.state;');
    w('  var all = ' + moduleVar + '.query(state, ' + _jsStr(firstColl) + ', null);');
    w("  assertEqual(all.length, 2, 'query all returns 2');");
    w("  var active = " + moduleVar + ".query(state, " + _jsStr(firstColl) + ", { status: 'active' });");
    w("  assertEqual(active.length, 1, 'query filtered returns 1');");
    w("  var none = " + moduleVar + ".query(state, 'nonexistent_collection', {});");
    w("  assertEqual(none.length, 0, 'query nonexistent collection returns empty');");
    w('})();');
    w('');

    // Results
    w('// --- Results ---');
    w('');
    w("console.log('\\n" + moduleName + " Tests: ' + passed + ' passed, ' + failed + ' failed');");
    w('if (failed > 0) {');
    w('  process.exit(1);');
    w('} else {');
    w("  console.log('All " + name + " simulation tests passed!');");
    w('}');

    return lines.join('\n') + '\n';
  }

  // ---------------------------------------------------------------------------
  // forge — all-in-one: parse + generate everything
  // ---------------------------------------------------------------------------

  function forge(specInput) {
    var spec = parseSpec(specInput);
    var moduleSource = generateModule(spec);
    var initialState = generateState(spec);
    var testSource = generateTests(spec);
    return {
      name: spec.name,
      moduleSource: moduleSource,
      initialState: initialState,
      testSource: testSource
    };
  }

  // ---------------------------------------------------------------------------
  // loadAndRun — parse spec, generate module, eval it, return running instance
  // ---------------------------------------------------------------------------

  function loadAndRun(specInput) {
    var spec = parseSpec(specInput);
    var moduleSource = generateModule(spec);

    // The generated module uses the UMD pattern:
    // (function(exports) { ... })(typeof module !== 'undefined' ? module.exports : (window.SimXxx = {}));
    //
    // To eval it safely in any environment (browser or Node), we provide a
    // mock `module` object with an `exports` property. The UMD will detect
    // `typeof module !== 'undefined'` as true and write into mockModule.exports.
    // We also provide a mock `window` in case it is referenced at all.
    var simModule;
    try {
      var mockModule = { exports: {} };
      var mockWindow = {};
      // Use Function constructor with explicit arguments to sandbox the eval
      var factory = new Function('module', 'exports', 'window', moduleSource);
      factory(mockModule, mockModule.exports, mockWindow);
      simModule = mockModule.exports;
    } catch (e) {
      throw new Error('loadAndRun: failed to eval generated module for "' + spec.name + '": ' + e.message);
    }

    // Auto-initialize state
    simModule.initState();

    return simModule;
  }

  // ---------------------------------------------------------------------------
  // getExampleSpecs — built-in example spec objects for players to explore
  // ---------------------------------------------------------------------------

  function getExampleSpecs() {
    return [
      {
        name: 'todo',
        description: 'A simple todo list simulation',
        collections: {
          tasks: {
            fields: ['title', 'done', 'priority', 'due_date', 'notes']
          }
        },
        actions: ['create', 'update', 'delete', 'complete']
      },
      {
        name: 'project_manager',
        description: 'A project management simulation',
        collections: {
          projects: {
            fields: ['title', 'status', 'owner', 'deadline', 'budget']
          },
          tasks: {
            fields: ['title', 'status', 'assignee', 'board_id', 'priority', 'done']
          },
          milestones: {
            fields: ['title', 'due_date', 'status']
          }
        },
        actions: ['create', 'update', 'delete', 'complete', 'assign', 'move']
      },
      {
        name: 'inventory',
        description: 'An inventory management simulation',
        collections: {
          items: {
            fields: ['name', 'quantity', 'category', 'unit_price', 'location', 'notes']
          },
          categories: {
            fields: ['name', 'description']
          },
          transactions: {
            fields: ['item_id', 'quantity', 'type', 'timestamp', 'notes']
          }
        },
        actions: ['create', 'update', 'delete']
      },
      {
        name: 'recipe_book',
        description: 'A recipe collection simulation',
        collections: {
          recipes: {
            fields: ['title', 'cuisine', 'prep_time', 'servings', 'difficulty', 'notes']
          },
          ingredients: {
            fields: ['name', 'quantity', 'unit', 'recipe_id']
          },
          tags: {
            fields: ['name', 'color']
          }
        },
        actions: ['create', 'update', 'delete']
      }
    ];
  }

  // ---------------------------------------------------------------------------
  // Public API
  // ---------------------------------------------------------------------------

  exports.parseSpec = parseSpec;
  exports.generateModule = generateModule;
  exports.generateState = generateState;
  exports.generateTests = generateTests;
  exports.forge = forge;
  exports.loadAndRun = loadAndRun;
  exports.getExampleSpecs = getExampleSpecs;

})(typeof module !== 'undefined' ? module.exports : (window.SimForge = {}));
