// sim_project_manager.js — A project management tool with boards, tasks, and sprints
// Auto-generated by sim_forge.py — Article XI: Simulations
// initState(snapshot), applyAction(state, message), getState(), getSchema()
(function(exports) {
  'use strict';

  // --- Schema ---

  var _schema = {
    collections: {
      'boards': { prefix: 'boa', fields: ['name', 'description', 'created_at'] },
      'tasks': { prefix: 'tas', fields: ['title', 'status', 'assignee', 'board_id', 'priority', 'due_date'] },
      'sprints': { prefix: 'spr', fields: ['name', 'start_date', 'end_date', 'board_id', 'status'] }
    }
  };

  var _state = null;
  var _idCounter = 0;

  // --- Utilities ---

  function clone(obj) {
    return JSON.parse(JSON.stringify(obj));
  }

  function generateId(prefix) {
    _idCounter++;
    return prefix + '_' + Date.now().toString(36) + '_' + _idCounter;
  }

  function objectKeys(obj) {
    var keys = [];
    for (var k in obj) {
      if (obj.hasOwnProperty(k)) { keys.push(k); }
    }
    return keys;
  }

  function mergeOwner(data, from) {
    var out = {};
    for (var k in data) {
      if (data.hasOwnProperty(k)) { out[k] = data[k]; }
    }
    if (!out.owner) { out.owner = from || 'system'; }
    return out;
  }

  // --- State Management ---

  function initState(snapshot) {
    var freshSchema = JSON.parse(JSON.stringify(_schema));
    if (snapshot && typeof snapshot === 'object') {
      // Restore id counter from existing records
      var maxNum = 0;
      var collNames = objectKeys((snapshot._schema || {}).collections || {});
      var specColls = ['boards', 'tasks', 'sprints'];
      for (var si = 0; si < specColls.length; si++) {
        if (collNames.indexOf(specColls[si]) === -1) { collNames.push(specColls[si]); }
      }
      for (var ci = 0; ci < collNames.length; ci++) {
        var coll = snapshot[collNames[ci]];
        if (coll && typeof coll === 'object' && !Array.isArray(coll)) {
          var ids = objectKeys(coll);
          for (var ii = 0; ii < ids.length; ii++) {
            var parts = ids[ii].split('_');
            var num = parseInt(parts[parts.length - 1], 10);
            if (!isNaN(num) && num > maxNum) { maxNum = num; }
          }
        }
      }
      _idCounter = maxNum;
      var loaded = clone(snapshot);
      if (!loaded._schema) { loaded._schema = freshSchema; }
      // Ensure all spec collections exist
      for (var sci = 0; sci < specColls.length; sci++) {
        if (!loaded[specColls[sci]]) { loaded[specColls[sci]] = {}; }
      }
      _state = loaded;
      return _state;
    }
    // Fresh state
    _idCounter = 0;
    _state = {
      _schema: freshSchema,
      _sim: 'project_manager',
      _created_at: new Date().toISOString()
    };
    _state['boards'] = {};
    _state['tasks'] = {};
    _state['sprints'] = {};
    return _state;
  }

  // --- CRUD Helpers ---

  function create_boards(state, data) {
    var s = clone(state);
    var id = generateId('boa');
    var record = {
      id: id,
      owner: data.owner || 'system',
      createdAt: new Date().toISOString()
    };
    for (var k in data) {
      if (data.hasOwnProperty(k)) { record[k] = data[k]; }
    }
    if (!record.name && !record.title) {
      record.name = 'Unnamed board';
    }
    s['boards'][id] = record;
    return { state: s, record: record };
  }

  function update_boards(state, id, data) {
    if (!state['boards'] || !state['boards'][id]) { return state; }
    var s = clone(state);
    var target = s['boards'][id];
    for (var k in data) {
      if (data.hasOwnProperty(k) && k !== 'id') { target[k] = data[k]; }
    }
    target.updatedAt = new Date().toISOString();
    return s;
  }

  function delete_boards(state, id) {
    if (!state['boards'] || !state['boards'][id]) { return state; }
    var s = clone(state);
    delete s['boards'][id];
    return s;
  }

  function create_tasks(state, data) {
    var s = clone(state);
    var id = generateId('tas');
    var record = {
      id: id,
      owner: data.owner || 'system',
      createdAt: new Date().toISOString()
    };
    for (var k in data) {
      if (data.hasOwnProperty(k)) { record[k] = data[k]; }
    }
    if (!record.name && !record.title) {
      record.name = 'Unnamed task';
    }
    s['tasks'][id] = record;
    return { state: s, record: record };
  }

  function update_tasks(state, id, data) {
    if (!state['tasks'] || !state['tasks'][id]) { return state; }
    var s = clone(state);
    var target = s['tasks'][id];
    for (var k in data) {
      if (data.hasOwnProperty(k) && k !== 'id') { target[k] = data[k]; }
    }
    target.updatedAt = new Date().toISOString();
    return s;
  }

  function delete_tasks(state, id) {
    if (!state['tasks'] || !state['tasks'][id]) { return state; }
    var s = clone(state);
    delete s['tasks'][id];
    return s;
  }

  function create_sprints(state, data) {
    var s = clone(state);
    var id = generateId('spr');
    var record = {
      id: id,
      owner: data.owner || 'system',
      createdAt: new Date().toISOString()
    };
    for (var k in data) {
      if (data.hasOwnProperty(k)) { record[k] = data[k]; }
    }
    if (!record.name && !record.title) {
      record.name = 'Unnamed sprint';
    }
    s['sprints'][id] = record;
    return { state: s, record: record };
  }

  function update_sprints(state, id, data) {
    if (!state['sprints'] || !state['sprints'][id]) { return state; }
    var s = clone(state);
    var target = s['sprints'][id];
    for (var k in data) {
      if (data.hasOwnProperty(k) && k !== 'id') { target[k] = data[k]; }
    }
    target.updatedAt = new Date().toISOString();
    return s;
  }

  function delete_sprints(state, id) {
    if (!state['sprints'] || !state['sprints'][id]) { return state; }
    var s = clone(state);
    delete s['sprints'][id];
    return s;
  }

  // --- Action Dispatch ---

  function applyAction(state, msg) {
    var payload = (msg && msg.payload) ? msg.payload : (msg || {});
    var action = payload.action || '';
    var data = payload.data || {};
    var from = (msg && msg.from) || payload.from || 'system';
    var result;

    if (!state || !state._schema) {
      state = initState(state);
    }

    switch (action) {
      case 'create_boards':
        result = create_boards(state, mergeOwner(data, from));
        return result.state;

      case 'update_boards':
        return update_boards(state, data.id, data);

      case 'delete_boards':
        return delete_boards(state, data.id);

      case 'create_tasks':
        result = create_tasks(state, mergeOwner(data, from));
        return result.state;

      case 'update_tasks':
        return update_tasks(state, data.id, data);

      case 'delete_tasks':
        return delete_tasks(state, data.id);

      case 'create_sprints':
        result = create_sprints(state, mergeOwner(data, from));
        return result.state;

      case 'update_sprints':
        return update_sprints(state, data.id, data);

      case 'delete_sprints':
        return delete_sprints(state, data.id);

      case 'assign_tasks':
        var sa = clone(state);
        if (sa['tasks'] && sa['tasks'][data.id]) {
          sa['tasks'][data.id].assignee = data.assignee || from;
          sa['tasks'][data.id].updatedAt = new Date().toISOString();
        }
        return sa;

      case 'move_tasks':
        var sm = clone(state);
        if (sm['tasks'] && sm['tasks'][data.id]) {
          sm['tasks'][data.id]['board_id'] = data.board_id;
          sm['tasks'][data.id].updatedAt = new Date().toISOString();
        }
        return sm;

      case 'move_sprints':
        var sm = clone(state);
        if (sm['sprints'] && sm['sprints'][data.id]) {
          sm['sprints'][data.id]['board_id'] = data.board_id;
          sm['sprints'][data.id].updatedAt = new Date().toISOString();
        }
        return sm;

      case 'complete_boards':
        var sc = clone(state);
        if (sc['boards'] && sc['boards'][data.id]) {
          sc['boards'][data.id].completedAt = new Date().toISOString();
        }
        return sc;

      case 'complete_tasks':
        var sc = clone(state);
        if (sc['tasks'] && sc['tasks'][data.id]) {
          sc['tasks'][data.id].status = 'completed';
          sc['tasks'][data.id].completedAt = new Date().toISOString();
        }
        return sc;

      case 'complete_sprints':
        var sc = clone(state);
        if (sc['sprints'] && sc['sprints'][data.id]) {
          sc['sprints'][data.id].status = 'completed';
          sc['sprints'][data.id].completedAt = new Date().toISOString();
        }
        return sc;

      default:
        return state;
    }
  }

  // --- Query ---

  function query(state, collName, filter) {
    var coll = state[collName];
    if (!coll || typeof coll !== 'object' || Array.isArray(coll)) { return []; }
    var results = [];
    var ids = objectKeys(coll);
    for (var i = 0; i < ids.length; i++) {
      var item = coll[ids[i]];
      if (!filter || matchesFilter(item, filter)) {
        results.push(item);
      }
    }
    return results;
  }

  function matchesFilter(item, filter) {
    for (var k in filter) {
      if (filter.hasOwnProperty(k)) {
        if (item[k] !== filter[k]) { return false; }
      }
    }
    return true;
  }

  // --- Public API ---

  exports.initState = function(snapshot) {
    return initState(snapshot);
  };

  exports.applyAction = function(state, msg) {
    return applyAction(state, msg);
  };

  exports.getState = function() {
    return JSON.parse(JSON.stringify(_state));
  };

  exports.getSchema = function() {
    return JSON.parse(JSON.stringify(_schema));
  };

  exports.query = function(state, collName, filter) {
    return query(state, collName, filter);
  };

  exports.create_boards = function(state, data) {
    return create_boards(state, data);
  };
  exports.update_boards = function(state, id, data) {
    return update_boards(state, id, data);
  };
  exports.delete_boards = function(state, id) {
    return delete_boards(state, id);
  };

  exports.create_tasks = function(state, data) {
    return create_tasks(state, data);
  };
  exports.update_tasks = function(state, id, data) {
    return update_tasks(state, id, data);
  };
  exports.delete_tasks = function(state, id) {
    return delete_tasks(state, id);
  };

  exports.create_sprints = function(state, data) {
    return create_sprints(state, data);
  };
  exports.update_sprints = function(state, id, data) {
    return update_sprints(state, id, data);
  };
  exports.delete_sprints = function(state, id) {
    return delete_sprints(state, id);
  };

})(typeof module !== 'undefined' ? module.exports : (window.SimProjectManager = {}));
