// sim_todo.js — A todo simulation
// Auto-generated by sim_forge.py — Article XI: Simulations
// initState(snapshot), applyAction(state, message), getState(), getSchema()
(function(exports) {
  'use strict';

  // --- Schema ---

  var _schema = {
    collections: {
      'items': { prefix: 'ite', fields: ['title', 'done'] }
    }
  };

  var _state = null;
  var _idCounter = 0;

  // --- Utilities ---

  function clone(obj) {
    return JSON.parse(JSON.stringify(obj));
  }

  function generateId(prefix) {
    _idCounter++;
    return prefix + '_' + Date.now().toString(36) + '_' + _idCounter;
  }

  function objectKeys(obj) {
    var keys = [];
    for (var k in obj) {
      if (obj.hasOwnProperty(k)) { keys.push(k); }
    }
    return keys;
  }

  function mergeOwner(data, from) {
    var out = {};
    for (var k in data) {
      if (data.hasOwnProperty(k)) { out[k] = data[k]; }
    }
    if (!out.owner) { out.owner = from || 'system'; }
    return out;
  }

  // --- State Management ---

  function initState(snapshot) {
    var freshSchema = JSON.parse(JSON.stringify(_schema));
    if (snapshot && typeof snapshot === 'object') {
      // Restore id counter from existing records
      var maxNum = 0;
      var collNames = objectKeys((snapshot._schema || {}).collections || {});
      var specColls = ['items'];
      for (var si = 0; si < specColls.length; si++) {
        if (collNames.indexOf(specColls[si]) === -1) { collNames.push(specColls[si]); }
      }
      for (var ci = 0; ci < collNames.length; ci++) {
        var coll = snapshot[collNames[ci]];
        if (coll && typeof coll === 'object' && !Array.isArray(coll)) {
          var ids = objectKeys(coll);
          for (var ii = 0; ii < ids.length; ii++) {
            var parts = ids[ii].split('_');
            var num = parseInt(parts[parts.length - 1], 10);
            if (!isNaN(num) && num > maxNum) { maxNum = num; }
          }
        }
      }
      _idCounter = maxNum;
      var loaded = clone(snapshot);
      if (!loaded._schema) { loaded._schema = freshSchema; }
      // Ensure all spec collections exist
      for (var sci = 0; sci < specColls.length; sci++) {
        if (!loaded[specColls[sci]]) { loaded[specColls[sci]] = {}; }
      }
      _state = loaded;
      return _state;
    }
    // Fresh state
    _idCounter = 0;
    _state = {
      _schema: freshSchema,
      _sim: 'todo',
      _created_at: new Date().toISOString()
    };
    _state['items'] = {};
    return _state;
  }

  // --- CRUD Helpers ---

  function create_items(state, data) {
    var s = clone(state);
    var id = generateId('ite');
    var record = {
      id: id,
      owner: data.owner || 'system',
      createdAt: new Date().toISOString()
    };
    for (var k in data) {
      if (data.hasOwnProperty(k)) { record[k] = data[k]; }
    }
    if (!record.name && !record.title) {
      record.name = 'Unnamed item';
    }
    s['items'][id] = record;
    return { state: s, record: record };
  }

  function update_items(state, id, data) {
    if (!state['items'] || !state['items'][id]) { return state; }
    var s = clone(state);
    var target = s['items'][id];
    for (var k in data) {
      if (data.hasOwnProperty(k) && k !== 'id') { target[k] = data[k]; }
    }
    target.updatedAt = new Date().toISOString();
    return s;
  }

  function delete_items(state, id) {
    if (!state['items'] || !state['items'][id]) { return state; }
    var s = clone(state);
    delete s['items'][id];
    return s;
  }

  // --- Action Dispatch ---

  function applyAction(state, msg) {
    var payload = (msg && msg.payload) ? msg.payload : (msg || {});
    var action = payload.action || '';
    var data = payload.data || {};
    var from = (msg && msg.from) || payload.from || 'system';
    var result;

    if (!state || !state._schema) {
      state = initState(state);
    }

    switch (action) {
      case 'create_items':
        result = create_items(state, mergeOwner(data, from));
        return result.state;

      case 'update_items':
        return update_items(state, data.id, data);

      case 'delete_items':
        return delete_items(state, data.id);

      case 'complete_items':
        var sc = clone(state);
        if (sc['items'] && sc['items'][data.id]) {
          sc['items'][data.id].done = true;
          sc['items'][data.id].completedAt = new Date().toISOString();
        }
        return sc;

      default:
        return state;
    }
  }

  // --- Query ---

  function query(state, collName, filter) {
    var coll = state[collName];
    if (!coll || typeof coll !== 'object' || Array.isArray(coll)) { return []; }
    var results = [];
    var ids = objectKeys(coll);
    for (var i = 0; i < ids.length; i++) {
      var item = coll[ids[i]];
      if (!filter || matchesFilter(item, filter)) {
        results.push(item);
      }
    }
    return results;
  }

  function matchesFilter(item, filter) {
    for (var k in filter) {
      if (filter.hasOwnProperty(k)) {
        if (item[k] !== filter[k]) { return false; }
      }
    }
    return true;
  }

  // --- Public API ---

  exports.initState = function(snapshot) {
    return initState(snapshot);
  };

  exports.applyAction = function(state, msg) {
    return applyAction(state, msg);
  };

  exports.getState = function() {
    return JSON.parse(JSON.stringify(_state));
  };

  exports.getSchema = function() {
    return JSON.parse(JSON.stringify(_schema));
  };

  exports.query = function(state, collName, filter) {
    return query(state, collName, filter);
  };

  exports.create_items = function(state, data) {
    return create_items(state, data);
  };
  exports.update_items = function(state, id, data) {
    return update_items(state, id, data);
  };
  exports.delete_items = function(state, id) {
    return delete_items(state, id);
  };

})(typeof module !== 'undefined' ? module.exports : (window.SimTodo = {}));
